Repository orderoutofchaos/kry-judge, pull requests merged in 2021-08, with the labels that each got.

#39 docker 설정
  .env.sample
  Dockerfile
  db/etc/mysql/conf.d/my.cnf
  db/initdb.d/init.sql
  docker-compose.yml
  src/main/resources/application.yml
  wait-for
Labels: feature

#32 Problem 리포지토리, 서비스, 컨트롤러 작성
  src/main/kotlin/org/oooc/kry/problem/controller/ProblemSetController.kt
  src/main/kotlin/org/oooc/kry/problem/repository/ProblemRepository.kt
  src/main/kotlin/org/oooc/kry/problem/service/ProblemService.kt
  src/main/resources/application.yml
  src/test/kotlin/org/oooc/kry/problem/entity/ProblemTest.kt
Labels: feature

#26 Problem 및 관련 엔티티 구현
  src/main/kotlin/org/oooc/kry/problem/controller/ProblemSetController.kt
  src/main/kotlin/org/oooc/kry/problem/entity/Problem.kt
  src/main/kotlin/org/oooc/kry/problem/entity/ProblemTag.kt
  src/main/kotlin/org/oooc/kry/problem/entity/ProblemUser.kt
  src/main/kotlin/org/oooc/kry/problem/entity/Tag.kt
  src/main/kotlin/org/oooc/kry/problem/entity/TestCase.kt
  src/main/kotlin/org/oooc/kry/problem/repository/ProblemRepository.kt
  src/main/kotlin/org/oooc/kry/problem/service/ProblemService.kt
  src/test/kotlin/org/oooc/kry/problem/entity/ProblemTest.kt
Labels: feature, discussion

#41 [ADD] SecurityConfig
  src/main/kotlin/org/oooc/kry/global/SecurityConfig.kt
Labels: bug

#42 .gitignore 수정
  .gitignore
Labels: enhancement

#44 [UPDATE] set server.error.include-stacktrace to "never"
  src/main/resources/application.yml
Labels: enhancement

#49 [UPDATE] init.sql for user
  db/initdb.d/init.sql
Labels: enhancement, feature

#48 Init sql 수정
  db/initdb.d/init.sql
Labels: enhancement, feature

#50 [UPDATE] initdb.d merge 완료
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/libraries-with-intellij-classes.xml
  .idea/runConfigurations.xml
  .idea/sqldialects.xml
  .idea/vcs.xml
  db/initdb.d/01-init.sql
  db/initdb.d/02-testdata.sql
  db/initdb.d/init.sql
  src/main/resources/application.yml
Labels: enhancement
